{% set name = "serde" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rossmacarthur/serde/archive/{{ version }}.tar.gz
  sha256: 91571c55604c34b076c3002028cfe805ffb47328e7ad15d5a5e812605175c8d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - isodate >=0.6
    - six >=1.13.0

test:
  imports:
    - serde

about:
  home: https://github.com/rossmacarthur/serde
  license: MIT OR Apache2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Define, serialize, deserialize, and validate Python data structures.
  doc_url: https://rossmacarthur.github.io/serde/
  dev_url: https://github.com/rossmacarthur/serde

extra:
  recipe-maintainers:
    - kellpossible
